---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: sgx_ubuntu2004
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    pre_build_image: true
    privileged: true
  - name: sgx_ubuntu2204
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    pre_build_image: true
    privileged: true
  - name: sgx_ubuntu2404
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest"
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
